apiVersion: extensions.agents.x-k8s.io/v1alpha1
kind: SandboxTemplate
metadata:
  name: python-cloudhv-template
  namespace: default
spec:
  podTemplate:
    spec:
      runtimeClassName: cloudhv
      automountServiceAccountToken: false
      nodeSelector:
        workload: cloudhv
      containers:
        - name: python-runtime
          image: us-central1-docker.pkg.dev/k8s-staging-images/agent-sandbox/python-runtime-sandbox:latest-main
          ports:
            - containerPort: 8888
          readinessProbe:
            httpGet:
              path: "/"
              port: 8888
            initialDelaySeconds: 15
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 20
          livenessProbe:
            httpGet:
              path: "/"
              port: 8888
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 10
          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              memory: "256Mi"
      restartPolicy: "OnFailure"
